# Generated by Django 6.0.6 on 2026-06-26 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('order', models.IntegerField(default=0)),
                ('is_vip', models.BooleanField(default=False)),
                ('is_class1', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام ورزشگاه')),
                ('capacity', models.IntegerField(verbose_name='ظرفیت کل')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=100, verbose_name='تیم میزبان')),
                ('away_team', models.CharField(max_length=100, verbose_name='تیم میهمان')),
                ('home_team_logo', models.ImageField(blank=True, null=True, upload_to='team_logos/')),
                ('away_team_logo', models.ImageField(blank=True, null=True, upload_to='team_logos/')),
                ('date_time', models.DateTimeField(verbose_name='تاریخ و ساعت برگزاری')),
                ('is_active', models.BooleanField(default=True)),
                ('total_capacity', models.IntegerField(default=0, verbose_name='ظرفیت کل')),
                ('sold_tickets', models.IntegerField(default=0, verbose_name='تعداد بلیط\u200cهای فروخته\u200cشده')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.stadium')),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='matches.block')),
            ],
            options={
                'ordering': ['block__order', 'number'],
                'unique_together': {('block', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='شماره صندلی')),
                ('is_available', models.BooleanField(default=True, verbose_name='موجود')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='matches.row', verbose_name='ردیف')),
            ],
            options={
                'verbose_name': 'صندلی',
                'verbose_name_plural': 'صندلی\u200cها',
                'unique_together': {('row', 'number')},
            },
        ),
        migrations.CreateModel(
            name='MatchSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True, verbose_name='موجود')),
                ('reserved_until', models.DateTimeField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_seats', to='matches.match')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_seats', to='matches.seat')),
            ],
            options={
                'verbose_name': 'صندلی مسابقه',
                'verbose_name_plural': 'صندلی\u200cهای مسابقه',
                'unique_together': {('match', 'seat')},
            },
        ),
    ]
