# Generated by Django 6.0.6 on 2026-06-26 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_block_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='price',
            field=models.DecimalField(decimal_places=0, default=50000, max_digits=10, verbose_name='قیمت (تومان)'),
        ),
    ]
