# Generated by Django 6.0.6 on 2026-06-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_block_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={},
        ),
        migrations.AddField(
            model_name='block',
            name='zone_type',
            field=models.CharField(choices=[('home', 'میزبان'), ('away', 'میهمان'), ('class1', 'کلاس ۱'), ('women', 'بانوان')], default='home', max_length=10, verbose_name='نوع جایگاه'),
        ),
        migrations.AlterField(
            model_name='block',
            name='price',
            field=models.DecimalField(decimal_places=0, default=50000, max_digits=10),
        ),
    ]
