# Generated by Django 6.0.6 on 2026-06-30 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_alter_block_options_block_zone_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='stadium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='matches.stadium', verbose_name='ورزشگاه'),
        ),
        migrations.AlterField(
            model_name='block',
            name='zone_type',
            field=models.CharField(choices=[('home', 'میزبان'), ('away', 'میهمان'), ('class1', 'کلاس ۱'), ('vip', 'VIP'), ('women', 'بانوان')], default='home', max_length=20, verbose_name='نوع بلوک'),
        ),
    ]
