# Generated by Django 6.0.6 on 2026-06-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_block_stadium_alter_block_zone_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ['order'], 'verbose_name': 'بلوک', 'verbose_name_plural': 'بلوک\u200cها'},
        ),
        migrations.AlterField(
            model_name='block',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='block',
            name='is_class1',
            field=models.BooleanField(default=False, verbose_name='کلاس ۱'),
        ),
        migrations.AlterField(
            model_name='block',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='VIP'),
        ),
        migrations.AlterField(
            model_name='block',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام بلوک'),
        ),
        migrations.AlterField(
            model_name='block',
            name='order',
            field=models.IntegerField(default=0, verbose_name='ترتیب'),
        ),
        migrations.AlterField(
            model_name='block',
            name='price',
            field=models.DecimalField(decimal_places=0, default=50000, max_digits=10, verbose_name='قیمت (تومان)'),
        ),
        migrations.AlterField(
            model_name='block',
            name='zone_type',
            field=models.CharField(choices=[('home', 'میزبان'), ('away', 'میهمان'), ('class1', 'کلاس ۱'), ('women', 'بانوان'), ('vip', 'VIP')], default='home', max_length=10, verbose_name='نوع جایگاه'),
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('stadium', 'name')},
        ),
    ]
