# Generated by Django 6.0.6 on 2026-06-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_alter_block_options_alter_block_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='sport_type',
            field=models.CharField(choices=[('football', 'فوتبال'), ('volleyball', 'والیبال'), ('handball', 'هندبال'), ('basketball', 'بسکتبال'), ('futsal', 'فوتسال'), ('other', 'سایر')], default='football', max_length=20, verbose_name='رشته ورزشی'),
        ),
    ]
