# Generated by Django 6.0.6 on 2026-07-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_match_sport_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام سکو'),
        ),
    ]
