# Generated by Django 6.0.6 on 2026-07-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_alter_block_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stadium_images/', verbose_name='تصویر ورزشگاه'),
        ),
    ]
