# Generated by Django 6.0.6 on 2026-07-14 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_stadium_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='توضیح هزینه')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ (تومان)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='matches.match')),
            ],
            options={
                'verbose_name': 'هزینه مسابقه',
                'verbose_name_plural': 'هزینه\u200cهای مسابقه',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchFinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_ticket_revenue', models.BigIntegerField(default=0, verbose_name='درآمد فروش بلیط')),
                ('total_ticket_sold', models.IntegerField(default=0, verbose_name='تعداد بلیط فروخته شده')),
                ('total_vip_tickets', models.IntegerField(default=0, verbose_name='تعداد بلیط VIP')),
                ('total_used_tickets', models.IntegerField(default=0, verbose_name='تعداد بلیط استفاده شده')),
                ('total_costs', models.BigIntegerField(default=0, verbose_name='مجموع هزینه\u200cها')),
                ('total_revenues', models.BigIntegerField(default=0, verbose_name='مجموع درآمدهای اضافی')),
                ('net_profit', models.BigIntegerField(default=0, verbose_name='سود خالص')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_report', to='matches.match')),
            ],
            options={
                'verbose_name': 'گزارش مالی مسابقه',
                'verbose_name_plural': 'گزارش\u200cهای مالی مسابقات',
            },
        ),
        migrations.CreateModel(
            name='MatchRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='توضیح درآمد')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ (تومان)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='matches.match')),
            ],
            options={
                'verbose_name': 'درآمد اضافی مسابقه',
                'verbose_name_plural': 'درآمدهای اضافی مسابقه',
                'ordering': ['-created_at'],
            },
        ),
    ]
