# Generated by Django 6.0.6 on 2026-07-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0010_matchcost_matchfinancialreport_matchrevenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchfinancialreport',
            name='total_wallet_usage',
            field=models.BigIntegerField(default=0, verbose_name='مبلغ استفاده شده از کیف پول'),
        ),
        migrations.AlterField(
            model_name='matchcost',
            name='amount',
            field=models.BigIntegerField(verbose_name='مبلغ (ریال)'),
        ),
        migrations.AlterField(
            model_name='matchrevenue',
            name='amount',
            field=models.BigIntegerField(verbose_name='مبلغ (ریال)'),
        ),
    ]
