# Generated by Django 6.0.6 on 2026-07-19 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0011_matchfinancialreport_total_wallet_usage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='total_capacity',
        ),
    ]
