# Generated by Django 6.0.6 on 2026-08-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0012_remove_match_total_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='price',
            field=models.DecimalField(decimal_places=0, default=50000, max_digits=10, verbose_name='قیمت (ریال)'),
        ),
    ]
