# Generated by Django 6.0.6 on 2026-08-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0013_alter_block_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='بلیط ویژه'),
        ),
        migrations.AlterField(
            model_name='block',
            name='zone_type',
            field=models.CharField(choices=[('home', 'میزبان'), ('away', 'میهمان'), ('class1', 'کلاس ۱'), ('women', 'بانوان'), ('vip', 'بلیط ویژه')], default='home', max_length=10, verbose_name='نوع جایگاه'),
        ),
        migrations.AlterField(
            model_name='matchfinancialreport',
            name='total_vip_tickets',
            field=models.IntegerField(default=0, verbose_name='تعداد بلیط ویژه'),
        ),
    ]
