# Generated by Django 6.0.6 on 2026-08-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0014_alter_block_is_vip_alter_block_zone_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='VIP'),
        ),
        migrations.AlterField(
            model_name='block',
            name='zone_type',
            field=models.CharField(choices=[('home', 'میزبان'), ('away', 'میهمان'), ('class1', 'کلاس ۱'), ('women', 'بانوان'), ('vip', 'VIP')], default='home', max_length=10, verbose_name='نوع جایگاه'),
        ),
    ]
