# Generated by Django 6.0.6 on 2026-08-29 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0021_matchbasadiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchseat',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='فعال برای این مسابقه'),
        ),
        migrations.CreateModel(
            name='MatchBlockActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(verbose_name='فعال')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_active_overrides', to='matches.block')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_active_overrides', to='matches.match')),
            ],
            options={
                'verbose_name': 'وضعیت اختصاصی بلوک برای مسابقه',
                'verbose_name_plural': 'وضعیت\u200cهای اختصاصی بلوک برای مسابقات',
                'unique_together': {('match', 'block')},
            },
        ),
        migrations.CreateModel(
            name='MatchRowActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(verbose_name='فعال')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_active_overrides', to='matches.match')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_active_overrides', to='matches.row')),
            ],
            options={
                'verbose_name': 'وضعیت اختصاصی ردیف برای مسابقه',
                'verbose_name_plural': 'وضعیت\u200cهای اختصاصی ردیف برای مسابقات',
                'unique_together': {('match', 'row')},
            },
        ),
    ]
