# Generated by Django 6.0.6 on 2026-08-29 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0022_matchseat_is_enabled_matchblockactive_matchrowactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchBlockZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_type', models.CharField(choices=[('home', 'میزبان'), ('away', 'میهمان'), ('class1', 'کلاس ۱'), ('women', 'بانوان'), ('vip', 'VIP')], max_length=10, verbose_name='نوع جایگاه')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_zone_overrides', to='matches.block')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_zone_overrides', to='matches.match')),
            ],
            options={
                'verbose_name': 'نوع جایگاه اختصاصی بلوک برای مسابقه',
                'verbose_name_plural': 'نوع جایگاه\u200cهای اختصاصی بلوک برای مسابقات',
                'unique_together': {('match', 'block')},
            },
        ),
    ]
