# Generated by Django 6.0.6 on 2026-08-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0024_alter_block_zone_type_alter_matchblockzone_zone_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='zone_type',
            field=models.CharField(choices=[('home', 'میزبان'), ('away', 'میهمان'), ('class1', 'کلاس ۱'), ('women', 'بانوان میزبان'), ('women_away', 'بانوان میهمان'), ('vip', 'VIP')], default='home', max_length=10, verbose_name='نوع جایگاه'),
        ),
        migrations.AlterField(
            model_name='matchblockzone',
            name='zone_type',
            field=models.CharField(choices=[('home', 'میزبان'), ('away', 'میهمان'), ('class1', 'کلاس ۱'), ('women', 'بانوان میزبان'), ('women_away', 'بانوان میهمان'), ('vip', 'VIP')], max_length=10, verbose_name='نوع جایگاه'),
        ),
    ]
