# Generated by Django 6.0.6 on 2026-08-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0025_alter_block_zone_type_alter_matchblockzone_zone_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='has_time',
            field=models.BooleanField(default=True, help_text='اگر خاموش باشد، ساعت بازی هیچ\u200cجا (بنر، بلیط، PDF) نمایش داده نمی\u200cشود.', verbose_name='ساعت بازی مشخص است'),
        ),
    ]
