# Generated by Django 6.0.6 on 2026-07-19 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0012_remove_match_total_capacity'),
        ('payments', '0001_initial'),
        ('tickets', '0006_ticket_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('wallet_charge', 'شارژ کیف پول'), ('ticket_purchase', 'پرداخت باقی\u200cمانده\u200cی خرید بلیط')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'در انتظار بازگشت از درگاه'), ('success', 'موفق'), ('failed', 'ناموفق')], default='pending', max_length=20)),
                ('track_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('gateway_amount', models.BigIntegerField(default=0, help_text='مبلغی که به درگاه فرستاده شده (ریال)')),
                ('buyer_info', models.JSONField(blank=True, default=dict)),
                ('seat_ids', models.JSONField(blank=True, default=list)),
                ('discount_code', models.CharField(blank=True, max_length=50)),
                ('discount_percent', models.IntegerField(default=0)),
                ('subtotal', models.BigIntegerField(default=0, help_text='قیمت کل قبل از تخفیف (ریال)')),
                ('discount_amount', models.BigIntegerField(default=0, help_text='مبلغ تخفیف (ریال)')),
                ('wallet_amount_used', models.BigIntegerField(default=0, help_text='مبلغی که قراره از کیف پول کسر بشه (ریال)')),
                ('next_url', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matches.match')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='tickets.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
