# Generated by Django 6.0.6 on 2026-09-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_gateway_captured_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gateway_checked_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='آخرین باری که وضعیت این پرداخت از درگاه استعلام شد (نتیجه هرچه بوده)', null=True),
        ),
    ]
