# Generated by Django 6.0.6 on 2026-08-08 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_national_code_user_is_phone_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(db_index=True, help_text='user:<id> یا ip:<آدرس>', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('visited_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'بازدید سایت',
                'verbose_name_plural': 'بازدیدهای سایت',
                'ordering': ['-visited_at'],
            },
        ),
    ]
