# Generated by Django 6.0.6 on 2026-08-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_sitevisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_foreign_ips', models.BooleanField(default=True, help_text='در صورت فعال بودن، فقط بازدیدکننده\u200cهایی با آی\u200cپی ایران می\u200cتوانند سایت را ببینند (پنل ادمین از این قانون همیشه مستثناست). با غیرفعال کردن این گزینه، آی\u200cپی\u200cهای خارج از ایران هم اجازه\u200cی اتصال پیدا می\u200cکنند.', verbose_name='مسدودسازی آی\u200cپی\u200cهای خارج از ایران')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
