# Generated by Django 6.0.6 on 2026-08-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_is_basa_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fan_id_subject',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True, verbose_name='Fan ID Subject'),
        ),
    ]
