# Generated by Django 6.0.6 on 2026-08-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_fan_id_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='wallet_enabled',
            field=models.BooleanField(default=True, help_text='با غیرفعال کردن این گزینه، کیف پول کاملاً از چرخه خارج می\u200cشود: کاربر نه می\u200cتواند کیف پولش را شارژ کند و نه می\u200cتواند بخشی از هزینه\u200cی بلیط را از کیف پول بپردازد. موجودی فعلی کاربران پاک نمی\u200cشود و صفحه\u200cی کیف پول برای دیدن موجودی و تاریخچه باز می\u200cماند؛ با فعال کردن دوباره، همان موجودی قبلی دوباره قابل استفاده است. بازگشت وجه (لغو مسابقه یا مابه\u200cالتفاوت پرداخت) همیشه — حتی در حالت غیرفعال — به کیف پول واریز می\u200cشود تا پول کاربر گم نشود.', verbose_name='فعال بودن کیف پول'),
        ),
    ]
