# Generated by Django 6.0.6 on 2026-08-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    # ===== عمداً به 0009 وصل است، نه به 0010 =====
    # 0010 (fan_id_subject) فقط روی شاخه‌ی feature/keycloak-sso وجود دارد و
    # روی main/پروداکشن نیست. این مایگریشن فیلدی به SiteSettings اضافه می‌کند
    # و هیچ ربطی به User ندارد، پس وابستگی واقعی‌اش همان 0009 است. روی شاخه‌ی
    # فیچر، مایگریشنِ merge دو سرِ 0010 و 0011 را به هم می‌رساند.
    dependencies = [
        ('accounts', '0009_user_is_basa_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='wallet_enabled',
            field=models.BooleanField(default=True, help_text='با غیرفعال کردن این گزینه، کیف پول کاملاً از چرخه خارج می\u200cشود: کاربر نه می\u200cتواند کیف پولش را شارژ کند و نه می\u200cتواند بخشی از هزینه\u200cی بلیط را از کیف پول بپردازد. موجودی فعلی کاربران پاک نمی\u200cشود و صفحه\u200cی کیف پول برای دیدن موجودی و تاریخچه باز می\u200cماند؛ با فعال کردن دوباره، همان موجودی قبلی دوباره قابل استفاده است. بازگشت وجه (لغو مسابقه یا مابه\u200cالتفاوت پرداخت) همیشه — حتی در حالت غیرفعال — به کیف پول واریز می\u200cشود تا پول کاربر گم نشود.', verbose_name='فعال بودن کیف پول'),
        ),
    ]
