# Generated by Django 6.0.6 on 2026-08-31 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    # ===== عمداً به 0011 وصل است، نه به 0012_merge =====
    # 0012_merge فقط روی شاخه‌ی feature/keycloak-sso وجود دارد (برای آشتی‌دادن
    # 0010 که مخصوص همان شاخه است). روی main آخرین مایگریشنِ accounts همان
    # 0011 است، پس اگر به 0012 وصل می‌شد، migrate روی پروداکشن با
    # NodeNotFoundError می‌خورد. روی شاخه‌ی فیچر یک merge دیگر دو سر را
    # به هم می‌رساند.
    dependencies = [
        ('accounts', '0011_sitesettings_wallet_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='free_under_15',
            field=models.BooleanField(default=True, help_text='در حالت فعال، هر بلیطی که سنِ تأییدشده\u200cی صاحبش کمتر از ۱۵ سال باشد رایگان می\u200cشود. با غیرفعال کردن، زیر ۱۵ ساله\u200cها هم مثل بقیه قیمت کامل بلوک را می\u200cپردازند (تخفیف باسا و کد تخفیف طبق روال عادی روی همان قیمت اعمال می\u200cشود). این تنظیم روی بلیط\u200cهایی که از قبل رایگان صادر شده\u200cاند اثری ندارد.', verbose_name='رایگان بودن بلیط برای زیر ۱۵ سال'),
        ),
    ]
