# Generated by Django 6.0.6 on 2026-09-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    # عمداً به ۰۰۱۵ وصل است و نه به ۰۰۱۶_merge: شاخه‌ی main مهاجرت‌های merge
    # را ندارد و ۰۰۱۵ آخرین گره‌ی مشترک دو شاخه است. اگر وابستگی به merge
    # می‌ماند، همین فایل موقع cherry-pick به main با NodeNotFoundError می‌شکست.
    dependencies = [
        ('accounts', '0015_sitesettings_wallet_charge_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='withdrawal_enabled',
            field=models.BooleanField(default=False, help_text='در حالت فعال، کاربر می\u200cتواند برای پولی که باشگاه به کیف پولش برگردانده (جبران بلیط صادرنشده، بازگشت وجه، پرداخت دوباره) درخواست برداشت به شبا ثبت کند. پولی که خودِ کاربر از درگاه شارژ کرده قابل برداشت نیست. هر درخواست باید در پنل تأیید و سپس به\u200cصورت دستی واریز شود؛ خاموش کردن این گزینه فقط جلوی ثبت درخواست تازه را می\u200cگیرد و درخواست\u200cهای در جریان را لغو نمی\u200cکند.', verbose_name='امکان برداشت وجه از کیف پول'),
        ),
    ]
