# Generated by Django 6.0.6 on 2026-07-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_wallet',
            field=models.BooleanField(default=True, help_text='آیا این تراکنش مستقیماً به کیف پول مربوط می\u200cشود؟', verbose_name='تراکنش کیف پول'),
        ),
    ]
