# Generated by Django 6.0.6 on 2026-07-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_transaction_is_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'شارژ'), ('withdraw', 'برداشت'), ('refund', 'بازگشت'), ('ticket_purchase', 'خرید بلیط')], max_length=20, verbose_name='نوع تراکنش'),
        ),
    ]
