# Generated by Django 6.0.6 on 2026-07-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.BigIntegerField(default=0, verbose_name='موجودی (ریال)'),
        ),
    ]
