# Generated by Django 6.0.6 on 2026-09-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_withdrawalrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تأیید شده — در انتظار واریز'), ('paid', 'واریز شد'), ('rejected', 'رد شد'), ('cancelled', 'لغو شده توسط شما')], db_index=True, default='pending', max_length=20),
        ),
    ]
