# Generated by Django 6.0.6 on 2026-09-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_alter_withdrawalrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='iban_owner_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='نام صاحب حساب نزد بانک'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='iban_verified',
            field=models.BooleanField(blank=True, null=True, verbose_name='تطابق نام با بانک'),
        ),
    ]
