# Generated by Django 6.0.6 on 2026-09-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_withdrawalrequest_iban_owner_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='کد ملی'),
        ),
    ]
