# Generated by Django 6.0.6 on 2026-09-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_withdrawalrequest_national_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تأیید'), ('needs_correction', 'نیاز به اصلاح اطلاعات'), ('approved', 'در انتظار پرداخت'), ('paid', 'پرداخت انجام شد'), ('rejected', 'رد شد'), ('cancelled', 'لغو شده توسط شما')], db_index=True, default='pending', max_length=20),
        ),
    ]
