"""
Django settings for football_tickets project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()  # بارگذاری متغیرهای .env
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q34y()@tsqsw^a$fi4&0#3urtv+9=wc0y5hu0(k$e*zunakk-j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'matches',
    'tickets',
    'payments',
    'crispy_forms',
    'wallet',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'football_tickets.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.site_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'football_tickets.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'sepahan_ticket',
#         'USER': 'sepahan_user',
#         'PASSWORD': 'kasra123',
#         'HOST': '127.0.0.1',
#         'PORT': '5432',
#     }
# }



# settings.py

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

# زمان رزرو (به ثانیه)
SEAT_RESERVATION_TIMEOUT = 600  # ۵ دقیقه

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [

]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
AUTH_USER_MODEL = 'accounts.User'

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]  # پوشه استاتیک در ریشه
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

PAYMENT_GATEWAY = {
    'sandbox': True,
    'merchant_id': 'your_merchant_id',
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'your_email@gmail.com'
EMAIL_HOST_PASSWORD = 'your_password'


# تنظیمات پیام‌ها
from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}

# ===== تنظیمات sms.ir =====
# football_tickets/settings.py

# ===== SMS.ir =====
# محیط Sandbox (True برای تست، False برای تولید)
SMS_IR_SANDBOX = True  # ← در لوکال True کنید

# کلید API مخصوص Sandbox (از پنل SMS.ir دریافت کنید)
SMS_IR_API_KEY = 'DOGayRyuWQjdxJxFYIhcGIeivpL2qNCIVvkDRfrnpqqk9gfd'

# URL متد Verify (برای Sandbox و Production یکسان است)
SMS_IR_SEND_URL = 'https://api.sms.ir/v1/send/verify'

# شناسه قالب (در Sandbox فقط 123456 معتبر است)
SMS_IR_TEMPLATE_ID = 123456  # پیش‌فرض Sandbox

# شماره خط (در Sandbox نیازی نیست، اما برای ساختار保持一致 می‌گذاریم)
SMS_IR_LINE_NUMBER = '1000xxxx'  # در Sandbox استفاده نمی‌شود

# تنظیمات زیبال
ZIBAL_MERCHANT_ID = os.getenv('ZIBAL_MERCHANT_ID', 'zibal')
ZIBAL_SANDBOX = os.getenv('ZIBAL_SANDBOX', 'True') == 'True'
ZIBAL_CALLBACK_URL = 'http://127.0.0.1:8000/payment/verify/'  # آدرس بازگشت

# ===== احراز هویت =====
AUTHENTICATION_BACKENDS = [
    'accounts.backends.PhoneBackend',  # برای OTP
    'django.contrib.auth.backends.ModelBackend',  # برای رمز عبور
]

# football_tickets/settings.py
# یا
LOGIN_URL = 'accounts:choose_login'  # صفحه انتخاب روش
LOGIN_REDIRECT_URL = 'matches:home'
LOGOUT_REDIRECT_URL = 'accounts:choose_login'
OTP_ENABLED = True
