# Generated by Django 6.0.6 on 2026-06-26 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('national_code', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('cancelled', 'لغو شده'), ('admin_assigned', 'تخصیص توسط ادمین'), ('vip_issued', 'صادرشده توسط کاربر ویژه')], default='paid', max_length=20)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='ticket_pdfs/')),
                ('ticket_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('is_admin_assigned', models.BooleanField(default=False, verbose_name='تخصیص توسط ادمین')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match', verbose_name='مسابقه')),
                ('match_seat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matches.matchseat', verbose_name='صندلی مسابقه (وضعیت هر مسابقه)')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.seat', verbose_name='صندلی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='VIPQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota', models.IntegerField(verbose_name='ظرفیت مجاز')),
                ('used', models.IntegerField(default=0, verbose_name='تعداد استفاده\u200cشده')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vip_quotas', to='matches.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vip_quotas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تخصیص ظرفیت',
                'verbose_name_plural': 'تخصیص ظرفیت\u200cها',
                'unique_together': {('user', 'match')},
            },
        ),
    ]
