# Generated by Django 6.0.6 on 2026-07-08 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_stadium_image'),
        ('tickets', '0003_discountcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='match',
            field=models.ForeignKey(blank=True, help_text='این کد تخفیف فقط برای این مسابقه معتبر است.', null=True, on_delete=django.db.models.deletion.CASCADE, to='matches.match', verbose_name='مسابقه'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matches.block', verbose_name='بلوک (اختیاری)'),
        ),
    ]
