# Generated by Django 6.0.6 on 2026-07-14 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_stadium_image'),
        ('tickets', '0004_discountcode_match_alter_discountcode_block'),
        ('wallet', '0003_alter_transaction_transaction_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها (Tickets)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('wallet.transaction',),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('subtotal', models.BigIntegerField(default=0, help_text='مبلغ کل قبل از تخفیف (تومان)')),
                ('discount_percent', models.IntegerField(default=0, help_text='درصد تخفیف')),
                ('discount_amount', models.BigIntegerField(default=0, help_text='مبلغ تخفیف (تومان)')),
                ('total_amount', models.BigIntegerField(default=0, help_text='مبلغ نهایی (تومان)')),
                ('wallet_amount', models.BigIntegerField(default=0, help_text='مبلغ پرداخت شده از کیف پول (تومان)')),
                ('wallet_balance_before', models.BigIntegerField(default=0, help_text='موجودی کیف پول قبل از خرید')),
                ('wallet_balance_after', models.BigIntegerField(default=0, help_text='موجودی کیف پول بعد از خرید')),
                ('payment_method', models.CharField(choices=[('wallet', 'کیف پول'), ('zibal', 'درگاه زیبال'), ('mixed', 'ترکیبی (کیف پول + زیبال)'), ('vip', 'صدور VIP'), ('admin', 'تخصیص ادمین')], default='wallet', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده')], default='pending', max_length=20)),
                ('track_id', models.CharField(blank=True, help_text='شناسه تراکنش درگاه', max_length=100, null=True)),
                ('discount_code', models.CharField(blank=True, help_text='کد تخفیف استفاده شده', max_length=50, null=True)),
                ('discount_code_id', models.IntegerField(blank=True, help_text='شناسه کد تخفیف', null=True)),
                ('full_name', models.CharField(blank=True, help_text='نام خریدار', max_length=200)),
                ('phone_number', models.CharField(blank=True, help_text='شماره تلفن خریدار', max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='matches.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='order',
            field=models.ForeignKey(blank=True, help_text='سفارش مربوط به این بلیط', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.order'),
        ),
    ]
