# Generated by Django 6.0.6 on 2026-07-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_transaction_order_ticket_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.BigIntegerField(default=0, verbose_name='قیمت (ریال)'),
        ),
    ]
