# Generated by Django 6.0.6 on 2026-08-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.BigIntegerField(default=0, help_text='مبلغ تخفیف (ریال)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.BigIntegerField(default=0, help_text='مبلغ کل قبل از تخفیف (ریال)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.BigIntegerField(default=0, help_text='مبلغ نهایی (ریال)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='wallet_amount',
            field=models.BigIntegerField(default=0, help_text='مبلغ پرداخت شده از کیف پول (ریال)'),
        ),
    ]
