# Generated by Django 6.0.6 on 2026-08-08 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_order_discount_amount_alter_order_subtotal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'بلیط', 'verbose_name_plural': 'بلیط\u200cها'},
        ),
    ]
