# Generated by Django 6.0.6 on 2026-08-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_alter_ticket_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('wallet', 'کیف پول'), ('zibal', 'درگاه زیبال'), ('mixed', 'ترکیبی (کیف پول + زیبال)'), ('vip', 'صدور بلیط ویژه'), ('admin', 'تخصیص ادمین')], default='wallet', max_length=20),
        ),
    ]
