# Generated by Django 6.0.6 on 2026-08-17 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_alter_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='discount_percent',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف'),
        ),
    ]
