# Generated by Django 6.0.6 on 2026-08-24 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_alter_discountcode_discount_percent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='vip_owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'vip'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vip_discount_codes', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ویژه (صاحب کد)'),
        ),
    ]
