# Generated by Django 6.0.6 on 2026-08-24 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_discountcode_vip_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.discountcode', verbose_name='کد تخفیف اعمال\u200cشده'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='discount_code_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ تخفیفِ کد (ریال)'),
        ),
    ]
