# Generated by Django 6.0.6 on 2026-08-25 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0021_matchbasadiscount'),
        ('tickets', '0018_fix_backfill_ticket_discount_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد ویژه')),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده\u200cشده')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان استفاده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_codes', to='matches.match', verbose_name='مسابقه')),
                ('vip_owner', models.ForeignKey(limit_choices_to={'user_type': 'vip'}, on_delete=django.db.models.deletion.CASCADE, related_name='special_codes', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ویژه (صاحب کد)')),
            ],
            options={
                'verbose_name': 'کد ویژه',
                'verbose_name_plural': 'کدهای ویژه',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='special_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.specialcode', verbose_name='کد ویژه اعمال\u200cشده'),
        ),
    ]
