# Generated by Django 6.0.6 on 2026-08-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_specialcode_ticket_special_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialcode',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
    ]
